# Generated by Django 4.1.4 on 2022-12-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='isPOpular',
            new_name='isPopular',
        ),
        migrations.AlterField(
            model_name='brand',
            name='img',
            field=models.ImageField(upload_to='brands', verbose_name='Photo of brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(upload_to='products', verbose_name='Photo of product'),
        ),
    ]
