# Generated by Django 4.1.4 on 2022-12-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_ispopular_product_ispopular_alter_brand_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Name of category')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Name of Subcategory')),
            ],
        ),
        migrations.RemoveField(
            model_name='shop',
            name='shopCount',
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(to='myapp.color', verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(to='myapp.size', verbose_name='Size'),
        ),
        migrations.CreateModel(
            name='ForWhom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='For Whom ?')),
                ('img', models.ImageField(upload_to='forWhom', verbose_name='Photo of brand')),
                ('categories', models.ManyToManyField(to='myapp.category', verbose_name='Category')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='subcategories',
            field=models.ManyToManyField(to='myapp.subcategory', verbose_name='Subcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='myapp.category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='forWhom',
            field=models.ManyToManyField(to='myapp.forwhom', verbose_name='For whom ?'),
        ),
        migrations.AddField(
            model_name='product',
            name='subCategory',
            field=models.ManyToManyField(to='myapp.subcategory', verbose_name='Subcategory'),
        ),
    ]
