# Generated by Django 4.1.4 on 2022-12-13 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_category_subcategories_subcategory_category'),
        ('myapp', '0003_category_subcategory_remove_shop_shopcount_and_more'),
    ]

    operations = [
    ]
