# Generated by Django 4.1.4 on 2022-12-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_product_count_remove_product_forwhom_product_forwhom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='count',
        ),
        migrations.AlterField(
            model_name='product',
            name='forWhom',
            field=models.CharField(choices=[('MEN', 'MEN'), ('WOMEN', 'WOMEN'), ('CHILDREN', 'CHILDREN')], max_length=10),
        ),
    ]
